# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_cf.orchestrator.swagger_server.models.base_model_ import Model
from fabric_cf.orchestrator.swagger_server.models.status200_ok_single import Status200OkSingle  # noqa: F401,E501
from fabric_cf.orchestrator.swagger_server import util


class Metrics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, size: int=1, status: int=200, type: str=None, results: List[object]=None):  # noqa: E501
        """Metrics - a model defined in Swagger

        :param size: The size of this Metrics.  # noqa: E501
        :type size: int
        :param status: The status of this Metrics.  # noqa: E501
        :type status: int
        :param type: The type of this Metrics.  # noqa: E501
        :type type: str
        :param results: The results of this Metrics.  # noqa: E501
        :type results: List[object]
        """
        self.swagger_types = {
            'size': int,
            'status': int,
            'type': str,
            'results': List[object]
        }

        self.attribute_map = {
            'size': 'size',
            'status': 'status',
            'type': 'type',
            'results': 'results'
        }
        self._size = size
        self._status = status
        self._type = type
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'Metrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The metrics of this Metrics.  # noqa: E501
        :rtype: Metrics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def size(self) -> int:
        """Gets the size of this Metrics.


        :return: The size of this Metrics.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this Metrics.


        :param size: The size of this Metrics.
        :type size: int
        """

        self._size = size

    @property
    def status(self) -> int:
        """Gets the status of this Metrics.


        :return: The status of this Metrics.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this Metrics.


        :param status: The status of this Metrics.
        :type status: int
        """

        self._status = status

    @property
    def type(self) -> str:
        """Gets the type of this Metrics.


        :return: The type of this Metrics.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Metrics.


        :param type: The type of this Metrics.
        :type type: str
        """

        self._type = type

    @property
    def results(self) -> List[object]:
        """Gets the results of this Metrics.


        :return: The results of this Metrics.
        :rtype: List[object]
        """
        return self._results

    @results.setter
    def results(self, results: List[object]):
        """Sets the results of this Metrics.


        :param results: The results of this Metrics.
        :type results: List[object]
        """

        self._results = results
