# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_cf.orchestrator.swagger_server.models.base_model_ import Model
from fabric_cf.orchestrator.swagger_server import util


class PoaData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: str=None):  # noqa: E501
        """PoaData - a model defined in Swagger

        :param data: The data of this PoaData.  # noqa: E501
        :type data: str
        """
        self.swagger_types = {
            'data': str
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'PoaData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The poa_data of this PoaData.  # noqa: E501
        :rtype: PoaData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> str:
        """Gets the data of this PoaData.


        :return: The data of this PoaData.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this PoaData.


        :param data: The data of this PoaData.
        :type data: str
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
