# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_cf.orchestrator.swagger_server.models.base_model_ import Model
from fabric_cf.orchestrator.swagger_server import util


class PoaDataInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, host: str=None, host_info: str=None, vm: str=None, vm_info: str=None):  # noqa: E501
        """PoaDataInfo - a model defined in Swagger

        :param host: The host of this PoaDataInfo.  # noqa: E501
        :type host: str
        :param host_info: The host_info of this PoaDataInfo.  # noqa: E501
        :type host_info: str
        :param vm: The vm of this PoaDataInfo.  # noqa: E501
        :type vm: str
        :param vm_info: The vm_info of this PoaDataInfo.  # noqa: E501
        :type vm_info: str
        """
        self.swagger_types = {
            'host': str,
            'host_info': str,
            'vm': str,
            'vm_info': str
        }

        self.attribute_map = {
            'host': 'host',
            'host_info': 'host_info',
            'vm': 'vm',
            'vm_info': 'vm_info'
        }
        self._host = host
        self._host_info = host_info
        self._vm = vm
        self._vm_info = vm_info

    @classmethod
    def from_dict(cls, dikt) -> 'PoaDataInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The poa_data_info of this PoaDataInfo.  # noqa: E501
        :rtype: PoaDataInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def host(self) -> str:
        """Gets the host of this PoaDataInfo.


        :return: The host of this PoaDataInfo.
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host: str):
        """Sets the host of this PoaDataInfo.


        :param host: The host of this PoaDataInfo.
        :type host: str
        """

        self._host = host

    @property
    def host_info(self) -> str:
        """Gets the host_info of this PoaDataInfo.


        :return: The host_info of this PoaDataInfo.
        :rtype: str
        """
        return self._host_info

    @host_info.setter
    def host_info(self, host_info: str):
        """Sets the host_info of this PoaDataInfo.


        :param host_info: The host_info of this PoaDataInfo.
        :type host_info: str
        """

        self._host_info = host_info

    @property
    def vm(self) -> str:
        """Gets the vm of this PoaDataInfo.


        :return: The vm of this PoaDataInfo.
        :rtype: str
        """
        return self._vm

    @vm.setter
    def vm(self, vm: str):
        """Sets the vm of this PoaDataInfo.


        :param vm: The vm of this PoaDataInfo.
        :type vm: str
        """

        self._vm = vm

    @property
    def vm_info(self) -> str:
        """Gets the vm_info of this PoaDataInfo.


        :return: The vm_info of this PoaDataInfo.
        :rtype: str
        """
        return self._vm_info

    @vm_info.setter
    def vm_info(self, vm_info: str):
        """Sets the vm_info of this PoaDataInfo.


        :param vm_info: The vm_info of this PoaDataInfo.
        :type vm_info: str
        """

        self._vm_info = vm_info
