FROM python:3.8.0
MAINTAINER Komal Thareja<komal.thareja@gmail.com>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
VOLUME ["/usr/src/app"]

COPY broker.sh /usr/src/app
RUN pip3 install --upgrade pip

EXPOSE 11000

ENTRYPOINT ["/usr/src/app/broker.sh"]
