FROM python:3.8.0
MAINTAINER Komal Thareja<komal.thareja@gmail.com>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
VOLUME ["/usr/src/app"]

RUN pip3 install --upgrade pip

EXPOSE 11000

#COPY authority.sh /usr/src/app
#ENTRYPOINT ["/usr/src/app/authority.sh"]

RUN pip3 install git+https://github.com/fabric-testbed/ControlFramework.git@listresources
RUN mkdir -p "/etc/fabric/message_bus/schema"
RUN cp /usr/local/lib/python3.8/site-packages/fabric/message_bus/schema/*.avsc /etc/fabric/message_bus/schema

ENTRYPOINT ["python3"]
CMD ["-m", "fabric.authority"]