version: '3.6'
services:

  neo4j:
    image: fabrictestbed/neo4j-apoc:5.3.0
    container_name: broker-neo4j
    user: ${NEO4J_UID:-1000}:${NEO4J_GID:-1000}
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - ${NEO4J_DATA_PATH_HOST:-$(pwd)/neo4j/data}:${NEO4J_DATA_PATH_DOCKER:-/data}
      - ${NEO4J_IMPORTS_PATH_HOST:-$(pwd)/neo4j/imports}:${NEO4J_IMPORTS_PATH_DOCKER:-/imports}
      - ${NEO4J_LOGS_PATH_HOST:-$(pwd)/neo4j/logs}:${NEO4J_LOGS_PATH_DOCKER:-/logs}
      - ../../../neo4j/certs/fullchain.pem:/ssl/neo4j.cert:ro  # SSL development certificate
      - ../../../neo4j/certs/privkey.pem:/ssl/neo4j.key:ro     # SSL development key
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASS:-password}
      - NEO4J_server_bolt_advertised__address=${NEO4J_server_bolt_advertised__address:-server:7687}
      - NEO4J_server_bolt_listen__address=${NEO4J_server_bolt_advertised__address:-server:7687}
      - NEO4J_server_http_advertised__address=${NEO4J_server_http_advertised__address:-server:7474}
      - NEO4J_server_http_listen__address=${NEO4J_server_http_advertised__address:-server:7474}
      - NEO4J_server_https_advertised__address=${NEO4J_server_https_advertised__address:-server:7473}
      - NEO4J_server_https_listen__address=${NEO4J_server_https_advertised__address:-server:7473}
      - NEO4J_server_memory_pagecache_size=${NEO4J_server_memory_pagecache_size:-512M}
  database:
    image: fabrictestbed/postgres:12.3
    container_name: broker-db
    restart: always
    networks:
      - backend
    volumes:
      - ./pg_data/data:${PGDATA:-/var/lib/postgresql/data}
      - ./pg_data/logs:${POSTGRES_INITDB_WALDIR:-/var/log/postgresql}
    environment:
       - POSTGRES_HOST=${POSTGRES_HOST:-database}
       - POSTGRES_PORT=5432
       - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB:-postgres}
       - POSTGRES_USER=${POSTGRES_USER:-postgres}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-broker}
       - PGDATA=${PGDATA:-/var/lib/postgresql/data}
  pdp:
    image: fabrictestbed/authzforce-pdp:6.0.1
    container_name: broker-pdp
    restart: always
    user: ${PDP_UID:-1000}:${PDP_GID:-1000}
    networks:
      - backend
    volumes:
      - ${PDP_NEW_CONF_PATH_HOST:-$(pwd)/newconf}:/conf
      - ${PDP_NEW_POLICIES_PATH_HOST:-$(pwd)/newpolicies}:/policies
  broker:
    build:
      context: ../../../
      dockerfile: Dockerfile-broker
    image: broker:1.6.0
    container_name: broker
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - database
      - neo4j
    ports:
      - 0.0.0.0:11000:11000
    volumes:
      - ./neo4j:/usr/src/app/neo4j
      - ./config.yaml:/etc/fabric/actor/config/config.yaml
      - ./logs/:/var/log/actor
      - ../../../secrets/snakeoil-ca-1.crt:/etc/fabric/message_bus/ssl/cacert.pem
      - ../../../secrets/kafkacat1.client.key:/etc/fabric/message_bus/ssl/client.key
      - ../../../secrets/kafkacat1-ca1-signed.pem:/etc/fabric/message_bus/ssl/client.pem
      #- ./state_recovery.lock:/usr/src/app/state_recovery.lock
networks:
  frontend:
  backend:
    internal: true
